name: Daily Model Training

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

jobs:
  train-and-commit:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run training script
        run: python main.py
        
      # --- THIS IS THE NEW DEBUGGING STEP ---
      - name: Verify that files were created
        run: |
          echo "Listing all files and directories recursively:"
          ls -R
      # --- END NEW STEP ---
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Automated daily model training"
          # We will try to commit everything in the folder
          file_pattern: 'trained_models/*'

